### ISSUE TITLE
Remove unused variable "errno"

### ISSUE THREAD

**Issue by elfring** [ChrisDodd/btyacc#4]
It seems that [the variable "errno"](https://github.com/ChrisDodd/btyacc/blob/bdaaa2ab318d94ea1e602742a4e099296eb59551/defs.h#L330 "") is not used in the provided source files so far after its definition.
Would you like to delete it so that confusion with [other specifications](https://en.wikipedia.org/wiki/Errno.h "Description for 'errno'") can be avoided?

**Comment by ChrisDodd** [comment]
fixed by 44d052229be4e1deb231d655813c21854fecd04f

**Comment by elfring** [comment]
Thanks for [a small source code improvement](https://github.com/ChrisDodd/btyacc/commit/4ff5a9efbebe0fe31d4c38313646a065a4702841#diff-cd8fcd138233b1197fe096b5e47e0eafL330 "Make VS2013 cl compiler happy with prefixed C runtime entry points.").

Would you like to delete also [the include statement for this variable](https://github.com/ChrisDodd/btyacc/blob/5d8967af6d6164220e11bcf5dde153c63298b367/defs.h#L336 "Is the inclusion of “errno.h” unnecessary?")?
