### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [ChrisDodd/btyacc#9]
The function "[exit](http://pubs.opengroup.org/onlinepubs/9699919799/functions/exit.html "Terminate a process.")" does not belong to the list of [async-signal-safe functions](https://www.securecoding.cert.org/confluence/display/c/SIG30-C.+Call+only+asynchronous-safe+functions+within+signal+handlers "Call only asynchronous-safe functions within signal handlers.").
I guess that a different program design will be needed for your function "[onintr](https://github.com/ChrisDodd/btyacc/blob/bdaaa2ab318d94ea1e602742a4e099296eb59551/main.c#L78 "Reconsider signal handling implementation.")".

**Comment by ChrisDodd** [comment]
onintr is for basic cleanup after a ctrl-C or other user interrupt -- output corruption is expected and unimportant in this case.

**Comment by elfring** [comment]
Would you like to consider other software design options?
* [sigwaitinfo()](http://pubs.opengroup.org/onlinepubs/9699919799/functions/sigwaitinfo.html "wait for queued signals")
* [Self-pipe trick](http://cr.yp.to/docs/selfpipe.html "Use case description by Daniel J. Bernstein")
* [Signal-safe locks](http://locklessinc.com/articles/signalsafe_locks/ "lock-free algorithms")
